### PR TITLE
Adding Type Declarations

### PR DESCRIPTION
**Pull request by askerushiro**
Just like with https://github.com/tshelburne/relax-client/pull/6 -- Adding in types.

### CODE REVIEW

**Review by tshelburne — CHANGES_REQUESTED** [review]
I'd like for this to cover a bit more ground - we should at least have the public interface typed. Also, what's the point of the tsconfig.json if we aren't running `tsc`?

**Comment by askerushiro** [comment]
@tshelburne Removed tsconfig.json and typed the exported methods. Looking a bit closer?

**Review by tshelburne — CHANGES_REQUESTED** [review]
Yea, now that I'm seeing this here, I think the library actually needs to be converted to TS and have the type files generated in the compilation step. There are a bunch of problems in there that wouldn't make it through if it were done in the code.

I think we can just close this for now - if you want to open another where the library is written with TS, feel free.

**Comment by tshelburne** [comment]
Closing in favor of eventually writing library itself in TS.

**Pull request closed without merging**
